name: Run "cabal check" with the latest setup

on:
  workflow_call:
    inputs:
      ghc:
        description: GHC version to use. For example, "8.10.7" or "latest".
        type: string
        default: latest

jobs:
  cabal-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up build tools
        id: setup
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ inputs.ghc }}

      - name: Check cabal file
        shell: bash
        run: cabal check
