name: Run "cabal haddock" with the latest setup

on:
  workflow_call:
    inputs:
      ghc:
        description: GHC version to use. For example, "8.10.7" or "latest".
        type: string
        default: latest

jobs:
  haddock:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Restore cached GHCup installations
        uses: actions/cache/restore@v4
        id: ghcup-cache
        with:
          path: ~/.ghcup
          key: ghcup-${{ runner.os }}-${{ inputs.ghc }}
          restore-keys: ghcup-${{ runner.os }}-

      - name: Set up build tools
        id: setup
        uses: haskell-actions/setup@v2
        with:
          ghc-version: ${{ inputs.ghc }}

      - name: Save GHCup installations cache
        uses: actions/cache/save@v4
        if: ${{ steps.ghcup-cache.outputs.cache-hit != 'true' }}
        with:
          path: ~/.ghcup
          key: ghcup-${{ runner.os }}-${{ inputs.ghc }}

      - name: Configure
        shell: bash
        run: >
          cabal configure --enable-documentation

      - name: Generate the plan
        shell: bash
        run: cabal build all --dry-run

      - name: Restore cached dependencies
        uses: actions/cache/restore@v4
        id: cache
        env:
          key: ${{ runner.os }}-${{ steps.setup.outputs.cabal-version }}-${{ steps.setup.outputs.ghc-version }}-${{ github.job }}
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ env.key }}-${{ hashFiles('**/plan.json') }}
          restore-keys: ${{ env.key }}

      - name: Install dependencies
        shell: bash
        run: cabal build all --only-dependencies -j +RTS -A128m -n2m -N -RTS

      - name: Save dependencies cache
        uses: actions/cache/save@v4
        if: ${{ steps.cache.outputs.cache-primary-key != steps.cache.outputs.cache-matched-key }}
        with:
          path: ${{ steps.setup.outputs.cabal-store }}
          key: ${{ steps.cache.outputs.cache-primary-key }}

      - name: Build docs
        shell: bash
        run: cabal haddock -j +RTS -A128m -n2m -N -RTS
